name: flutter_secure_storage_example
description: Demonstrates how to use the flutter_secure_storage plugin.

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage:
    # When depending on this package from a real application you should use:
    #   flutter_secure_storage: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter_secure_storage_platform_interface:
    path: ../../flutter_secure_storage_platform_interface

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  test: any

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_secure_storage_linux:
    path: ../../flutter_secure_storage_linux
  flutter_secure_storage_macos:
    path: ../../flutter_secure_storage_macos
  flutter_secure_storage_platform_interface:
    path: ../../flutter_secure_storage_platform_interface
  flutter_secure_storage_web:
    path: ../../flutter_secure_storage_web
  flutter_secure_storage_windows:
    path: ../../flutter_secure_storage_windows
