name: flutter_secure_storage_macos
description: macOS implementation of flutter_secure_storage
repository: https://github.com/mogol/flutter_secure_storage
publish_to: none
version: 3.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    path: ../flutter_secure_storage_platform_interface

flutter:
  plugin:
    implements: flutter_secure_storage
    platforms:
      macos:
        pluginClass: FlutterSecureStoragePlugin
