name: flutter_secure_storage
description: Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
version: 9.0.0
publish_to: none
repository: https://github.com/mogol/flutter_secure_storage/tree/develop/flutter_secure_storage

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        pluginClass: FlutterSecureStoragePlugin
      linux:
        default_package: flutter_secure_storage_linux
      macos:
        default_package: flutter_secure_storage_macos
      web:
        default_package: flutter_secure_storage_web
      windows:
        default_package: flutter_secure_storage_windows

dependencies:
  flutter:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # implementation constraints as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # https://github.com/flutter/flutter/issues/46264
  flutter_secure_storage_linux:
    path: ../flutter_secure_storage_linux
  flutter_secure_storage_macos:
    path: ../flutter_secure_storage_macos
  flutter_secure_storage_platform_interface:
    path: ../flutter_secure_storage_platform_interface
  flutter_secure_storage_web:
    path: ../flutter_secure_storage_web
  flutter_secure_storage_windows:
    path: ../flutter_secure_storage_windows
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

# We need to manually declare supported platforms, because pub.dev won't find them.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: