name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage. Use flutter_secure_storage for the full flutter package.
repository: https://github.com/mogol/flutter_secure_storage
publish_to: none
version: 1.1.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git: https://github.com/sumitsharansatsangi/flutter_secure_storage_platform_interface.git
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  lint: ^2.1.2

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
