name: flutter_secure_storage_windows
description: Windows implementation of flutter_secure_storage. Please use flutter_secure_storage instead of this package.
repository: https://github.com/mogol/flutter_secure_storage
publish_to: none
version: 3.0.0


environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git: https://github.com/kumsumit/flutter_secure_storage_platform_interface.git
  path: ^1.8.3
  path_provider: 
    git: https://github.com/kumsumit/path_provider.git
  win32: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  plugin:
    implements: flutter_secure_storage
    platforms:
      windows:
        pluginClass: FlutterSecureStorageWindowsPlugin
        dartPluginClass: FlutterSecureStorageWindows
